<form name="edit" action="<?=$action?>"
	  method="post" class="recordEdit"
	  <?
	  if($hasFileInput)
		  echo "enctype=\"multipart/form-data\"";
	  else
		  echo "enctype=\"application/x-www-form-urlencoded\"";
		  ?>>
	<table class="inputSet">
		<tr>
			<td>
				<ul>
		<? foreach($inputs as $i => $input) {
			if($i > 0 && $i % 5 === 0) echo "</ul></td><td><ul>";
			echo "<li>$input</li>";
		}
		?>
				</ul>
			</td>
		</tr>
		<tr>
			<td colspan="<?=ceil(count($inputs)/5)?>">
			<ul class="editFormButtons">
				<li><input type="submit" name="submit" value="Save"/></li>
				<li><a class="button" href="<?=$callbackLink?>">Cancel</a></li>
				<?
					if($hasFileInput)
					{
						?>
						<li><a class="button" href="download">Download</a></li>
					<?}
				?>
			</ul>
			</td>
		</tr>
	</table>
</form>