<div class="loginForm">
	<?= $feedbackView ?>
	<form class="loginForm" name="forgotPassword"
		  method="post" action="<?=$formAction?>">
		<ul>
			<li>
				<label for="<?=$usernameInputName?>">Username:</label>
				<input id="<?=$usernameInputName?>"
					   type="text" name="<?=$usernameInputName?>"/>
			</li>
			<li><input type="submit" name="action" value="Get Reset Link"/></li>
		</ul>
	</form>
</div>